# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription This endpoint registers a user.If you need to update a profile image, upload the profile image in thebackground using `/avatar` endpoint.
@apiVersion 1.0.0
@api {POST} api/v1/register Register
@apiGroup Auth
@apiParam {String} device_id Unique ID of the device
@apiParam {String} device_type Type of the device `APPLE` or `ANDROID`
@apiParam {String} [device_push_token] Unique push token for the device
@apiParam {String} email Email address of user
@apiParam {String} password Password. Must be at least 8 characters.
@apiParam {String} password_confirmation Confirm password. Must be at least 8 characters.
@apiHeader {String} Accept `application/json`
@apiHeader {String} x-api-key API Key
@apiErrorExample {json} Error-Response / HTTP 422 Unprocessable Content
{
					"message": "The email must be a valid email address.",
					"payload": {
						"errors": {
							"email": [
								"The email must be a valid email address."
							]
						}
					},
					"result": false
				}
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/login Login
@apiGroup Auth
@apiParam {String} device_id Unique ID of the device
@apiParam {String} device_type Type of the device `APPLE` or `ANDROID`
@apiParam {String} [device_push_token] Unique push token for the device
@apiParam {String} email Email
@apiParam {String} password Password
@apiHeader {String} Accept `application/json`
@apiHeader {String} x-api-key API Key
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {GET} api/v1/verify-email/{code} Email Verification
@apiGroup Auth
@apiParam {Integer} code Verification Code
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {GET} api/v1/resend-code Resend Verification Code
@apiGroup Auth
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Logout the user from current device
@apiVersion 1.0.0
@api {GET} api/v1/logout Logout
@apiGroup Auth
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/password/edit Update Password
@apiGroup Auth
@apiParam {String} password Password
@apiParam {String} current_password Current password
@apiParam {String} password_confirmation Password confirmation
@apiUse default_headers
###
