# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Use this endpoint to upload all files, including player images. You must use the `uuid` that gets returned, and use it to attach the file to other objects.
@apiVersion 1.0.0
@api {POST} api/v1/files Upload files
@apiGroup FilesAPI
@apiParam {String} file Image file to upload. Upload as a form field.
@apiParam {String} allow_public_access Pass True to enable public access, else false
@apiUse default_headers
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
    "payload": {
        "key": "file_key_f488eb9a-6ed9-4cf3-b32b-2f9c5f91bda4",
        "original_filename": "image.jpg",
        "file_url": "\/storage\/files\/202206\/tcfMxPDOGjc9Mve.jpg",
        "uuid": "ea39f5a0-0118-45f6-b0e9-cb18d876f680",
        "permalink": "http:\/\/boost.test\/files\/ea39f5a0-0118-45f6-b0e9-cb18d876f680\/image.jpg"
    },
    "message": "",
    "result": true
}
###
