# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get the team porformance
@apiVersion 1.0.0
@api {GET} api/v1/team-performance Team Performance
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get the team porformance PDF link from permalink param of the response
@apiVersion 1.0.0
@api {GET} api/v1/team-performance-pdf Team Performance PDF
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get the player porformance
@apiVersion 1.0.0
@api {GET} api/v1/player-performance Player Performance
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiParam {Integer} player_id Player ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get the Player porformance PDF link from permalink param of the response
@apiVersion 1.0.0
@api {GET} api/v1/player-performance-pdf Player Performance PDF
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiParam {Integer} player_id Player ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Store the tesm porformance comment
@apiVersion 1.0.0
@api {POST} api/v1/team-performance-comment Team Performance Comment
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiParam {String} comment performance comment
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Store the player porformance comment
@apiVersion 1.0.0
@api {POST} api/v1/player-performance-comment Player Performance Comment
@apiGroup Performance
@apiParam {Integer} player_id player id
@apiParam {Integer} team_id Team ID
@apiParam {String} comment performance comment
@apiUse default_headers
###
