# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get the team porformance
@apiVersion 1.0.0
@api {GET} api/v1/team-performance Team Performance
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get the team porformance PDF link from permalink param of the response
@apiVersion 1.0.0
@api {GET} api/v1/team-performance-pdf Team Performance PDF
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get the player porformance
@apiVersion 1.0.0
@api {GET} api/v1/player-performance Player Performance
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiParam {Integer} player_id Player ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get the Player porformance PDF link from permalink param of the response
@apiVersion 1.0.0
@api {GET} api/v1/player-performance-pdf Player Performance PDF
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiParam {Integer} player_id Player ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Store the tesm porformance comment
@apiVersion 1.0.0
@api {POST} api/v1/team-performance-comment Team Performance Comment
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiParam {String} comment performance comment
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Store the player porformance comment
@apiVersion 1.0.0
@api {POST} api/v1/player-performance-comment Player Performance Comment
@apiGroup Performance
@apiParam {Integer} player_id player id
@apiParam {Integer} team_id Team ID
@apiParam {String} comment performance comment
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Team player and game time
@apiVersion 1.0.0
@api {GET} api/v1/team-players Team Players with game time
@apiGroup Performance
@apiParam {String} page Page number
@apiParam {Integer} game_id Game ID
@apiParam {Integer} team_id Team ID
@apiUse default_headers
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
                    "payload": [
                        {
                            "id": 1,
                            "uuid": "0a0b846c-3811-46f0-b405-def00f9aef16",
                            "team_id": 1,
                            "image_uuid": null,
                            "name": "Nishshanka B",
                            "email": null,
                            "positions": "2",
                            "metadata": null,
                            "performance_notes": "second comment",
                            "prefered_positions": [
                                {
                                    "id": 2,
                                    "name": "Goal Defence",
                                    "short_name": "GD"
                                }
                            ],
                            "image": null,
                            "game_time": [
                                {
                                    "game_id": 2,
                                    "team_id": 1,
                                    "time_segment": "Quarter 1",
                                    "position_obj": {
                                        "id": 2,
                                        "name": "Goal Defence",
                                        "short_name": "GD"
                                    }
                                }
                            ]
                        }
                    ],
                    "paginator": {
                        "current_page": 1,
                        "first_page_url": "http://127.0.0.1:8000/api/v1/team-players?page=1",
                        "from": 1,
                        "last_page": 1,
                        "last_page_url": "http://127.0.0.1:8000/api/v1/team-players?page=1",
                        "links": [
                            {
                                "url": null,
                                "label": "&laquo; Previous",
                                "active": false
                            },
                            {
                                "url": "http://127.0.0.1:8000/api/v1/team-players?page=1",
                                "label": "1",
                                "active": true
                            },
                            {
                                "url": null,
                                "label": "Next &raquo;",
                                "active": false
                            }
                        ],
                        "next_page_url": null,
                        "path": "http://127.0.0.1:8000/api/v1/team-players",
                        "per_page": 15,
                        "prev_page_url": null,
                        "to": 1,
                        "total": 1
                    },
                    "message": "",
                    "result": true
                }
                
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get a list of finished games created by user. Pagination is supported. Played at time is in UTC. Convert to your timezone before using.
@apiVersion 1.0.0
@api {GET} api/v1/game-finished List Finished Games
@apiGroup Performance
@apiParam {Integer} team_id Team ID
@apiParam {String} page Page number
@apiUse default_headers
###
