# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get a list of teams created by user
@apiVersion 1.0.0
@api {GET} api/v1/teams List Teams
@apiGroup TeamsAPI
@apiParam {String} q Search query to filter by a name
@apiParam {String} page Page number
@apiUse default_headers
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
    "payload": {
        "current_page": 1,
        "data": [
            {
                "id": 3,
                "uuid": "510bf243-5320-4c85-949c-3df68519f2a0",
                "owner_id": 1,
                "image_uuid": null,
                "player_count": 12,
                "name": "Team C",
                "team_number": "LfLkN",
                "metadata": null,
                "performance_notes": "Error labore voluptate laboriosam voluptatem."
            },
            {
                "id": 2,
                "uuid": "64be0c03-093c-4f60-9d9f-7d8e86c1671f",
                "owner_id": 1,
                "image_uuid": null,
                "player_count": 14,
                "name": "Team B",
                "team_number": "9hEtz",
                "metadata": null,
                "performance_notes": "Fugiat incidunt aspernatur ea deserunt necessitatibus veniam eius."
            },
            {
                "id": 1,
                "uuid": "b24c645d-f139-4816-9564-0b7118e7bae4",
                "owner_id": 1,
                "image_uuid": null,
                "player_count": 14,
                "name": "Team A",
                "team_number": "G2H9K",
                "metadata": null,
                "performance_notes": "Sapiente placeat ut non tempora omnis commodi."
            }
        ],
        "first_page_url": "http:\/\/boost.test\/api\/v1\/teams?page=1",
        "from": 1,
        "last_page": 1,
        "last_page_url": "http:\/\/boost.test\/api\/v1\/teams?page=1",
        "links": [
            {
                "url": null,
                "label": "&laquo; Previous",
                "active": false
            },
            {
                "url": "http:\/\/boost.test\/api\/v1\/teams?page=1",
                "label": "1",
                "active": true
            },
            {
                "url": null,
                "label": "Next &raquo;",
                "active": false
            }
        ],
        "next_page_url": null,
        "path": "http:\/\/boost.test\/api\/v1\/teams",
        "per_page": 50,
        "prev_page_url": null,
        "to": 3,
        "total": 3
    },
    "message": "",
    "result": true
}
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/teams Create Team
@apiGroup TeamsAPI
@apiParam {String} name Team name
@apiParam {String} [team_number] A number for the team. Can be any value
@apiParam {String} [player_count] Number of players for the team
@apiParam {String} [image_uuid] UUID for the team profile picture. Get a UUID from file upload endpoint
@apiUse default_headers
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
    "payload": {
        "name": "Dare-Kovacek",
        "team_number": 13,
        "player_count": 13,
        "uuid": "989148b4-1c5a-4bfe-bbfe-db7daac23762",
        "id": 23,
        "owner_id": "1",
        "owner": {
            "uuid": "c1e7d9ce-f32b-428f-94bd-0e20a2bb87b6",
            "last_name": null,
            "email": "apps+user@elegantmedia.com.au",
            "email_verified_at": null,
            "avatar_url": null,
            "timezone": "Australia\/Melbourne",
            "first_name": "Peter Parker (REGULAR USER)",
            "full_name": "Peter Parker (REGULAR USER)"
        }
    },
    "message": "",
    "result": true
}
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {PUT} api/v1/teams/{uuid} Update Team
@apiGroup TeamsAPI
@apiParam {String} uuid uuid of the Team to update
@apiParam {String} name Team name
@apiParam {String} [team_number] A number for the team. Can be any value
@apiParam {String} [player_count] Number of players for the team
@apiParam {String} [image_uuid] UUID for the team profile picture. Get a UUID from file upload endpoint
@apiParam {String} [performance_notes] Team performance notes
@apiParam {String} metadata An array of key value pairs to store any metadata
@apiUse default_headers
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
    "payload": {
        "id": 1,
        "uuid": "b24c645d-f139-4816-9564-0b7118e7bae4",
        "owner_id": 1,
        "image_uuid": null,
        "player_count": 14,
        "name": "Jaylen Hill",
        "team_number": "G2H9K",
        "metadata": null,
        "performance_notes": "Rerum repellendus at recusandae quo adipisci."
    },
    "message": "",
    "result": true
}
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {DELETE} api/v1/teams/{uuid} Delete Team
@apiGroup TeamsAPI
@apiParam {String} uuid uuid of the Team to delete
@apiUse default_headers
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
    "payload": null,
    "message": "",
    "result": true
}
###
